spring:
  application:
    name: IntelliLearn
  datasource:
    url: jdbc:postgresql://localhost:5432/intellilearn
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  application.name:
    IntelliLearn

